#!/bin/bash

# ----
# SURROGATE database control utility
# ----

#
# Get configuration
#

source conf/s.conf
source lib/surrogate.lib

#
# Usage, getops
#

function usage() { 
cat << EOF
usage: $0 options

This script expects some arguments, please oblige!

OPTIONS:

-h	Shows this message
-b	Backup, either incremental or full, "-b incremental"
-r 	Restore, accepts the full path of a restore list "-r /path/to/file"
-c	Compress, compresses everything in 'last_backup'
-p	Promote

EOF
}

#
# Empty vars on initial call, reuse init() if needed
#

function init() {
type=""
restore=""
promote=""
}

init

[[ ! $1 ]] && { usage; }

while getopts "hb:r:p:c:" option 
do
	case $option in

		h)
		usage
		exit 1
		;;
	
		b)
		type=$OPTARG
		if [[ "$type" == "full" ]]; then
			fullbackup
		elif [[ "$type" == "inc" ]]; then
			incbackup
		else

			echo "Please specify full or incremental"
			exit 1
		fi
		;;
	
		r)
		restore=$OPTARG
		restorebackup
		;;

		c)
		compress=$OPTARG
		echo $compress
		compressbackup
		;;
		
		p)
		promote=$OPTARG
		# then run the promote case
		;;

	esac
done
