#!/bin/bash
# surrogate
# loren carvalho, 2012

# configs
source conf/surrogate.conf
source conf/xtrabackup.conf
source lib/surrogate.lib

# explain the usage
function usage() { 
cat <<-EOF
	usage: $0 options

	This script expects some arguments, please oblige!

	OPTIONS:

	-h	Shows this message
	-b	Backup, either incremental or full, "-b incremental"
	-r 	Restore, accepts the full path of a restore list "-r /path/to/file"
	
EOF
}

# empty vars on initial call, can reuse init() if needed
function init() {
type=""
restore=""
promote=""
}

init

# quietly run the rotation function
rotate_backups

# if there is no input, barf
[[ ! $1 ]] && { usage; }

# get input
while getopts "hb:r:" option 
	do
		case $option in
		h)
			usage
			exit 1
		;;
		b)
			type=$OPTARG
			if [[ "$type" == "full" ]]; then
				fullbackup
			elif [[ "$type" == "inc" ]]; then
				incbackup
			else	
				echo "Please specify full or incremental"
				exit 1
			fi
		;;
		r)
			restore=$OPTARG
			restorebackup
		;;
		esac
	done


# fin
