#!/usr/bin/env bash
# surrogate
# backup rotation/retention

function rotate_backups() {
	set -u
	find $backup_directory/daily/ -mindepth 2 -type f -mtime +${daily_retention} -exec rm {} \;
	find $backup_directory/weekly/ -type f -mtime +${weekly_retention} -exec rm {} \;
	find $backup_directory/monthly/ -type f -mtime +${monthly_retention} -exec rm {} \;

}
