#!/usr/bin/env bash
# surrogate
# primary library

# get config file(s)
for config in $(ls /etc/surrogate//);
	do
		source /etc/surrogate/$config
	done

# load all libs
for library in $(ls $my_root/lib/ | grep -v surrogate );
	do
		source $my_root/lib/$library
	done

# determine the location of todays backup (for retention)

if [[ `date +%d` == "01" ]]; 
  then
      full_backup_path="$backup_directory/monthly/full_$now"
elif [[ `date +%u` == "7" ]];
  then
      full_backup_path="$backup_directory/weekly/full_$now"
else
      full_backup_path="$backup_directory/daily/`date +%a`/full_$now"
fi

# fin
