#!/usr/bin/env bash
# surrogate
# mysql full backup function
function perform_action() {
  instance=$1

  if [ -z "$socket" ]; then
    socket_variable=mysql_socket_${instance}
    socket=${!socket_variable}
  fi

# dont need
#  determine_full_backup_path
#  if [ ! -d `dirname $full_backup_path` ]; then
#    mkdir -p `dirname $full_backup_path`
#  fi


runbackup () {
	type=$1
	mkdir -vp $backup_directory/$type/$today
	dblist=`mysql -u $mysql_user -p${mysql_pass} -S $mysql_socket -se "show databases"  | grep -v ^Database$`
	echo "creating full backup using mysqldump"
	for database in $dblist; do
        	mysqldump $dump_opts $database | gzip $gzip_opts > $backup_directory/$type/$today_iso_8601/$database.gz || dump_err=`expr $dump_err + 1`
	done

	test $dump_err -eq 0 && echo "status=0" > /tmp/backup-full.status || echo "status=1" > /tmp/backup-full.status
# logfile_f
#	eval retention=\$$type
# rotation elsewhere?
#        find $backup_directory/$type/ -type d -mtime +$retention | xargs -i rm -fvR {}
#	exit

}
 
# monthly 
if [ `date +%d` == $monthly_backup ]; then 
        runbackup monthly
fi
 
# weekly 
if [ `date +%a` == $weekly_backup ]; then  
        runbackup weekly
fi
 
# daily
runbackup daily

# fin
}
