#!/usr/bin/env bash
# surrogate
# incremental backup function

function perform_action() {
  instance=$1
  
  if [ -z "$socket" ]; then
    socket_variable=mysql_socket_${instance}
    socket=${!socket_variable}
  fi

  echo "creating incremental backup"

  #perform incremental backup from where the last backup stoped
  innobackupex 				\
  --ibbackup=xtrabackup_55 		\
  --parallel=8 				\
  --user=$mysql_user 			\
  --password=$mysql_pass 			\
  --no-timestamp 				\
  --compress \
  --compress-threads=8 \
  --incremental 				\
  --incremental-basedir=$last_backup 	\
  --socket=$socket \
  --defaults-group="mysqld$instance" \
  $inc_backup_path 2> $logfile_i

  echo "checking if the backup completed sucsessfully"
  if ! tail $logfile_i -n 1 | grep completed.OK
  then
    rm -R $inc_backup_path
    echo "\nERROR: backup failed! (log: "$logfile_i")"
    exit 1
  fi

  echo $inc_backup_path >> $backup_directory/.digest
  echo "Backup Completed OK!"
}

# fin
