#!/bin/bash
# surrogate
# mysql collapse backup script

function collapsebackup() {
echo "collapsing " $full_backup

# get last full backup location
full_backup=`head $collapse -n 1`

checkvar $full_backup
checkvar $backup_directory
checkvar $backup_filename
checkvar $incremental_backup
checkvar $active_incremental

echo $full_backup

if [ -d $active_backup ];
	then
	rm -R $active_backup
fi

echo "copying full backup files: " $full_backup
mkdir -p $active_backup
rsync -a $full_backup/ $active_backup/
echo "preparing full backup..."
innobackupex 			\
--ibbackup=xtrabackup_55 	\
--parallel=4 			\
--user=$mysql_user 		\
--password=$mysql_pass 		\
--apply-log 			\
--redo-only $active_backup 2> $logfile_c

echo "checking if the apply-log completed succsessfully"
if ! tail $logfile_c -n 1 | grep completed.OK
	then
       	echo "\nERROR: collapse failed! (log: "$logfile_c") "
		rm -R $active_backup
	        exit 1
fi

grep _in $collapse | while read $incremental_backup ; do
if [ -d $active_incremental ];
	then
		rm -R $active_incremental
fi
done

echo "copying incremental backup: " $incremental_backup
mkdir $active_incremental
cp -r $incremental_backup/ $active_incremental/
find $incremental_backup -name .delta -empty -maxdepth 2 -exec rm {} \;

echo "preparing incremetal backup..."
innobackupex 			\
--ibbackup=xtrabackup_55 	\
--parallel=4 			\
--user=$mysql_user 		\
--password=$mysql_pass 		\
--apply-log 			\
--redo-only $active_backup 	\
--incremental-dir=$active_incremental 2>> $logfile_c

rm -R $active_incremental

echo "checking if the apply incremental completed sucsessfully"
if ! tail $logfile_c -n 1 | grep completed.OK
	then
        	echo "\nERROR: collapse failed! (log: "$logfile_c")"
         	rm -R $active_backup
         	exit 1
fi

echo "applying Logs"
innobackupex 			\
--ibbackup=xtrabackup_55 	\
--parallel=4 			\
--user=$mysql_user 		\
--password=$mysql_pass 		\
--apply-log $active_backup 2>> $logfile_c

echo "saving collapsed backup..."
mkdir -p $backup_directory/$backup_filename
mv $active_backup/* $backup_directory/$backup_filename

## echo "compressing with tar"
## tar -czf $mysql_collapse_path/$backup_filename.tgz $backup_directory/$backup_filename
 
echo "removing stale data"
rm -rf $backup_directory/$backup_filename/*
rmdir $backup_directory/$backup_filename

echo "delete some tmp dirs"
rm -R $mysql_log_path/*
mkdir $mysql_log_path/bin
if [ -d $active_backup ];
	then
		rmdir $active_backup
fi

echo "Collapse Completed OK!"
}

# fin
