#!/usr/bin/env bash
# surrogate
# incremental backup function

function incbackup() {
echo "creating incremental backup"

#perform incremental backup from where the last backup stoped
innobackupex 				\
--ibbackup=xtrabackup_55 		\
--parallel=8 				\
--user=$mysql_user 			\
--password=$mysql_pass 			\
--no-timestamp 				\
--incremental 				\
--incremental-basedir=$last_backup 	\
$inc_backup_path 2> $logfile_i

echo "checking if the backup completed sucsessfully"
if ! tail $logfile_i -n 1 | grep completed.OK
	then
        	rm -R $inc_backup_path
	        echo "\nERROR: backup failed! (log: "$logfile_i")"
		exit 1
fi

echo $inc_backup_path >> $backup_directory/.digest
echo "Backup Completed OK!"
}

# fin
