#!/bin/bash
# surrogate
# loren carvalho, 2012
set -u

# configs
source /etc/surrogate/surrogate.conf
source /etc/surrogate/xtrabackup.conf
source /usr/local/lib/surrogate/lib/surrogate.lib

# explain the usage
function usage() { 
cat <<-EOF
	usage: $0 options

	This script must be run with sudo or as root, 
  it also expects some arguments, please oblige!

	OPTIONS:

	-h	Shows this message
	-b	Backup, either incremental or full, 
      "surrogate -b full" or "surrogate -b inc"
	-r 	Restore, accepts the full path of a restorable directory
	
EOF
exit 1
}

if [ "$(whoami)" != "root" ]; then
  usage
fi

# empty vars on initial call, can reuse init() if needed
function init() {
  type=""
  restore=""
  promote=""
}

init

# quietly run the rotation function
rotate_backups

# if there is no input, barf
[[ ! $1 ]] && { usage; }

# get input
while getopts "hb:r:" option 
	do
		case $option in
		h)
			usage
			exit 1
		;;
		b)
			type=$OPTARG
			if [[ "$type" == "full" ]]; then
				fullbackup
			elif [[ "$type" == "inc" ]]; then
				incbackup
			else	
				echo "Please specify full or incremental"
				usage
			fi
		;;
		r)
			restore=$OPTARG
			restorebackup
		;;
		esac
	done


# fin
